export const BorrowerOperationsAbi = [
  {
    inputs: [
      {
        internalType: "contract IAddressesRegistry",
        name: "_addressesRegistry",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AnnualManagementFeeTooHigh", type: "error" },
  { inputs: [], name: "BatchInterestRateChangePeriodNotPassed", type: "error" },
  { inputs: [], name: "BatchManagerExists", type: "error" },
  { inputs: [], name: "BatchManagerNotNew", type: "error" },
  { inputs: [], name: "BatchSharesRatioTooLow", type: "error" },
  { inputs: [], name: "CallerNotPriceFeed", type: "error" },
  { inputs: [], name: "CallerNotTroveManager", type: "error" },
  { inputs: [], name: "CollWithdrawalTooHigh", type: "error" },
  { inputs: [], name: "DebtBelowMin", type: "error" },
  {
    inputs: [],
    name: "DelegateInterestRateChangePeriodNotPassed",
    type: "error",
  },
  { inputs: [], name: "EmptyManager", type: "error" },
  { inputs: [], name: "ICRBelowMCR", type: "error" },
  { inputs: [], name: "ICRBelowMCRPlusBCR", type: "error" },
  { inputs: [], name: "InterestNotInRange", type: "error" },
  { inputs: [], name: "InterestRateNotNew", type: "error" },
  { inputs: [], name: "InterestRateTooHigh", type: "error" },
  { inputs: [], name: "InterestRateTooLow", type: "error" },
  { inputs: [], name: "InvalidInterestBatchManager", type: "error" },
  { inputs: [], name: "IsShutDown", type: "error" },
  { inputs: [], name: "MinGeMax", type: "error" },
  { inputs: [], name: "MinInterestRateChangePeriodTooLow", type: "error" },
  { inputs: [], name: "NewFeeNotLower", type: "error" },
  { inputs: [], name: "NewOracleFailureDetected", type: "error" },
  { inputs: [], name: "NotBorrower", type: "error" },
  { inputs: [], name: "NotEnoughBoldBalance", type: "error" },
  { inputs: [], name: "NotOwnerNorAddManager", type: "error" },
  { inputs: [], name: "NotOwnerNorInterestManager", type: "error" },
  { inputs: [], name: "NotOwnerNorRemoveManager", type: "error" },
  { inputs: [], name: "RepaymentNotMatchingCollWithdrawal", type: "error" },
  { inputs: [], name: "TCRBelowCCR", type: "error" },
  { inputs: [], name: "TCRNotBelowSCR", type: "error" },
  { inputs: [], name: "TroveExists", type: "error" },
  { inputs: [], name: "TroveInBatch", type: "error" },
  { inputs: [], name: "TroveNotActive", type: "error" },
  { inputs: [], name: "TroveNotInBatch", type: "error" },
  { inputs: [], name: "TroveNotOpen", type: "error" },
  { inputs: [], name: "TroveNotZombie", type: "error" },
  { inputs: [], name: "TroveWithZeroDebt", type: "error" },
  { inputs: [], name: "UpfrontFeeTooHigh", type: "error" },
  { inputs: [], name: "ZeroAdjustment", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_newActivePoolAddress",
        type: "address",
      },
    ],
    name: "ActivePoolAddressChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_troveId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_newAddManager",
        type: "address",
      },
    ],
    name: "AddManagerUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_boldTokenAddress",
        type: "address",
      },
    ],
    name: "BoldTokenAddressChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_collSurplusPoolAddress",
        type: "address",
      },
    ],
    name: "CollSurplusPoolAddressChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_newDefaultPoolAddress",
        type: "address",
      },
    ],
    name: "DefaultPoolAddressChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_gasPoolAddress",
        type: "address",
      },
    ],
    name: "GasPoolAddressChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_newPriceFeedAddress",
        type: "address",
      },
    ],
    name: "PriceFeedAddressChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_troveId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_newRemoveManager",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_newReceiver",
        type: "address",
      },
    ],
    name: "RemoveManagerAndReceiverUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_tcr",
        type: "uint256",
      },
    ],
    name: "ShutDown",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_sortedTrovesAddress",
        type: "address",
      },
    ],
    name: "SortedTrovesAddressChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_newTroveManagerAddress",
        type: "address",
      },
    ],
    name: "TroveManagerAddressChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_newTroveNFTAddress",
        type: "address",
      },
    ],
    name: "TroveNFTAddressChanged",
    type: "event",
  },
  {
    inputs: [],
    name: "BCR",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CCR",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MCR",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SCR",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "activePool",
    outputs: [
      { internalType: "contract IActivePool", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_troveId", type: "uint256" },
      { internalType: "uint256", name: "_collAmount", type: "uint256" },
    ],
    name: "addColl",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "addManagerOf",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_troveId", type: "uint256" },
      { internalType: "uint256", name: "_collChange", type: "uint256" },
      { internalType: "bool", name: "_isCollIncrease", type: "bool" },
      { internalType: "uint256", name: "_boldChange", type: "uint256" },
      { internalType: "bool", name: "_isDebtIncrease", type: "bool" },
      { internalType: "uint256", name: "_maxUpfrontFee", type: "uint256" },
    ],
    name: "adjustTrove",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_troveId", type: "uint256" },
      {
        internalType: "uint256",
        name: "_newAnnualInterestRate",
        type: "uint256",
      },
      { internalType: "uint256", name: "_upperHint", type: "uint256" },
      { internalType: "uint256", name: "_lowerHint", type: "uint256" },
      { internalType: "uint256", name: "_maxUpfrontFee", type: "uint256" },
    ],
    name: "adjustTroveInterestRate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_troveId", type: "uint256" },
      { internalType: "uint256", name: "_collChange", type: "uint256" },
      { internalType: "bool", name: "_isCollIncrease", type: "bool" },
      { internalType: "uint256", name: "_boldChange", type: "uint256" },
      { internalType: "bool", name: "_isDebtIncrease", type: "bool" },
      { internalType: "uint256", name: "_upperHint", type: "uint256" },
      { internalType: "uint256", name: "_lowerHint", type: "uint256" },
      { internalType: "uint256", name: "_maxUpfrontFee", type: "uint256" },
    ],
    name: "adjustZombieTrove",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_troveId", type: "uint256" },
      { internalType: "uint256", name: "_lowerHint", type: "uint256" },
      { internalType: "uint256", name: "_upperHint", type: "uint256" },
    ],
    name: "applyPendingDebt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_batchManager", type: "address" },
    ],
    name: "checkBatchManagerExists",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "claimCollateral",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_troveId", type: "uint256" }],
    name: "closeTrove",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getEntireBranchColl",
    outputs: [
      { internalType: "uint256", name: "entireSystemColl", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getEntireBranchDebt",
    outputs: [
      { internalType: "uint256", name: "entireSystemDebt", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_account", type: "address" }],
    name: "getInterestBatchManager",
    outputs: [
      {
        components: [
          { internalType: "uint128", name: "minInterestRate", type: "uint128" },
          { internalType: "uint128", name: "maxInterestRate", type: "uint128" },
          {
            internalType: "uint256",
            name: "minInterestRateChangePeriod",
            type: "uint256",
          },
        ],
        internalType: "struct IBorrowerOperations.InterestBatchManager",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_troveId", type: "uint256" }],
    name: "getInterestIndividualDelegateOf",
    outputs: [
      {
        components: [
          { internalType: "address", name: "account", type: "address" },
          { internalType: "uint128", name: "minInterestRate", type: "uint128" },
          { internalType: "uint128", name: "maxInterestRate", type: "uint128" },
          {
            internalType: "uint256",
            name: "minInterestRateChangePeriod",
            type: "uint256",
          },
        ],
        internalType: "struct IBorrowerOperations.InterestIndividualDelegate",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "hasBeenShutDown",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "interestBatchManagerOf",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_troveId", type: "uint256" },
      { internalType: "uint256", name: "_upperHint", type: "uint256" },
      { internalType: "uint256", name: "_lowerHint", type: "uint256" },
    ],
    name: "kickFromBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newAnnualManagementFee",
        type: "uint256",
      },
    ],
    name: "lowerBatchManagementFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_troveId", type: "uint256" }],
    name: "onLiquidateTrove",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_owner", type: "address" },
      { internalType: "uint256", name: "_ownerIndex", type: "uint256" },
      { internalType: "uint256", name: "_collAmount", type: "uint256" },
      { internalType: "uint256", name: "_boldAmount", type: "uint256" },
      { internalType: "uint256", name: "_upperHint", type: "uint256" },
      { internalType: "uint256", name: "_lowerHint", type: "uint256" },
      { internalType: "uint256", name: "_annualInterestRate", type: "uint256" },
      { internalType: "uint256", name: "_maxUpfrontFee", type: "uint256" },
      { internalType: "address", name: "_addManager", type: "address" },
      { internalType: "address", name: "_removeManager", type: "address" },
      { internalType: "address", name: "_receiver", type: "address" },
    ],
    name: "openTrove",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "owner", type: "address" },
          { internalType: "uint256", name: "ownerIndex", type: "uint256" },
          { internalType: "uint256", name: "collAmount", type: "uint256" },
          { internalType: "uint256", name: "boldAmount", type: "uint256" },
          { internalType: "uint256", name: "upperHint", type: "uint256" },
          { internalType: "uint256", name: "lowerHint", type: "uint256" },
          {
            internalType: "address",
            name: "interestBatchManager",
            type: "address",
          },
          { internalType: "uint256", name: "maxUpfrontFee", type: "uint256" },
          { internalType: "address", name: "addManager", type: "address" },
          { internalType: "address", name: "removeManager", type: "address" },
          { internalType: "address", name: "receiver", type: "address" },
        ],
        internalType:
          "struct IBorrowerOperations.OpenTroveAndJoinInterestBatchManagerParams",
        name: "_params",
        type: "tuple",
      },
    ],
    name: "openTroveAndJoinInterestBatchManager",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint128", name: "_minInterestRate", type: "uint128" },
      { internalType: "uint128", name: "_maxInterestRate", type: "uint128" },
      {
        internalType: "uint128",
        name: "_currentInterestRate",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "_annualManagementFee",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "_minInterestRateChangePeriod",
        type: "uint128",
      },
    ],
    name: "registerBatchManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_troveId", type: "uint256" },
      {
        internalType: "uint256",
        name: "_newAnnualInterestRate",
        type: "uint256",
      },
      { internalType: "uint256", name: "_upperHint", type: "uint256" },
      { internalType: "uint256", name: "_lowerHint", type: "uint256" },
      { internalType: "uint256", name: "_maxUpfrontFee", type: "uint256" },
    ],
    name: "removeFromBatch",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_troveId", type: "uint256" }],
    name: "removeInterestIndividualDelegate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "removeManagerReceiverOf",
    outputs: [
      { internalType: "address", name: "manager", type: "address" },
      { internalType: "address", name: "receiver", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_troveId", type: "uint256" },
      { internalType: "uint256", name: "_boldAmount", type: "uint256" },
    ],
    name: "repayBold",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_troveId", type: "uint256" },
      { internalType: "address", name: "_manager", type: "address" },
    ],
    name: "setAddManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "_newAnnualInterestRate",
        type: "uint128",
      },
      { internalType: "uint256", name: "_upperHint", type: "uint256" },
      { internalType: "uint256", name: "_lowerHint", type: "uint256" },
      { internalType: "uint256", name: "_maxUpfrontFee", type: "uint256" },
    ],
    name: "setBatchManagerAnnualInterestRate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_troveId", type: "uint256" },
      { internalType: "address", name: "_newBatchManager", type: "address" },
      { internalType: "uint256", name: "_upperHint", type: "uint256" },
      { internalType: "uint256", name: "_lowerHint", type: "uint256" },
      { internalType: "uint256", name: "_maxUpfrontFee", type: "uint256" },
    ],
    name: "setInterestBatchManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_troveId", type: "uint256" },
      { internalType: "address", name: "_delegate", type: "address" },
      { internalType: "uint128", name: "_minInterestRate", type: "uint128" },
      { internalType: "uint128", name: "_maxInterestRate", type: "uint128" },
      {
        internalType: "uint256",
        name: "_newAnnualInterestRate",
        type: "uint256",
      },
      { internalType: "uint256", name: "_upperHint", type: "uint256" },
      { internalType: "uint256", name: "_lowerHint", type: "uint256" },
      { internalType: "uint256", name: "_maxUpfrontFee", type: "uint256" },
      {
        internalType: "uint256",
        name: "_minInterestRateChangePeriod",
        type: "uint256",
      },
    ],
    name: "setInterestIndividualDelegate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_troveId", type: "uint256" },
      { internalType: "address", name: "_manager", type: "address" },
    ],
    name: "setRemoveManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_troveId", type: "uint256" },
      { internalType: "address", name: "_manager", type: "address" },
      { internalType: "address", name: "_receiver", type: "address" },
    ],
    name: "setRemoveManagerWithReceiver",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "shutdown",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "shutdownFromOracleFailure",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_troveId", type: "uint256" },
      { internalType: "uint256", name: "_removeUpperHint", type: "uint256" },
      { internalType: "uint256", name: "_removeLowerHint", type: "uint256" },
      { internalType: "address", name: "_newBatchManager", type: "address" },
      { internalType: "uint256", name: "_addUpperHint", type: "uint256" },
      { internalType: "uint256", name: "_addLowerHint", type: "uint256" },
      { internalType: "uint256", name: "_maxUpfrontFee", type: "uint256" },
    ],
    name: "switchBatchManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_troveId", type: "uint256" },
      { internalType: "uint256", name: "_boldAmount", type: "uint256" },
      { internalType: "uint256", name: "_maxUpfrontFee", type: "uint256" },
    ],
    name: "withdrawBold",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_troveId", type: "uint256" },
      { internalType: "uint256", name: "_collWithdrawal", type: "uint256" },
    ],
    name: "withdrawColl",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
