export const UsdafFlashZapperAbi = [
  {
    inputs: [
      { name: "owner", type: "address" },
      { name: "owner_index", type: "uint256" },
      { name: "initial_collateral_amount", type: "uint256" },
      { name: "flash_loan_amount", type: "uint256" },
      { name: "usdaf_amount", type: "uint256" },
      { name: "upper_hint", type: "uint256" },
      { name: "lower_hint", type: "uint256" },
      { name: "annual_interest_rate", type: "uint256" },
      { name: "max_upfront_fee", type: "uint256" },
    ],
    name: "open_leveraged_trove",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { name: "trove_id", type: "uint256" },
      { name: "flash_loan_amount", type: "uint256" },
      { name: "usdaf_amount", type: "uint256" },
      { name: "max_upfront_fee", type: "uint256" },
    ],
    name: "lever_up_trove",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "trove_id", type: "uint256" },
      { name: "flash_loan_amount", type: "uint256" },
      { name: "min_usdaf_amount", type: "uint256" },
      { name: "collateral_amount", type: "uint256" },
    ],
    name: "lever_down_trove",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "initiator", type: "address" },
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "fee", type: "uint256" },
      { name: "data", type: "bytes" },
    ],
    name: "onFlashLoan",
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "USDAF",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CRVUSD",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "WETH",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "FLASH_LENDER",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "UNWRAPPED_COLLATERAL_TOKEN",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "COLLATERAL_TOKEN",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "TROVE_NFT",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "BORROWER_OPERATIONS",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "usdaf_exchange",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "collateral_exchange",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "usdaf_exchange", type: "address" },
      { name: "collateral_exchange", type: "address" },
      { name: "addresses_registry", type: "address" },
      { name: "unwrapped_collateral_token", type: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
] as const;
